### ISSUE TITLE
Crash with Wizard casting Weakness

### ISSUE THREAD

**Issue by WinDanesz** [WinDanesz/AncientSpellcraft#154]
```
java.lang.ClassCastException: net.minecraft.entity.EntityAreaEffectCloud cannot be cast to net.minecraft.entity.EntityLivingBase
    at com.windanesz.ancientspellcraft.spell.Weakness.onEntityHit(Weakness.java:34)
    at electroblob.wizardry.spell.SpellRay.shootSpell(SpellRay.java:277)
    at electroblob.wizardry.spell.SpellRay.cast(SpellRay.java:203)
    at electroblob.wizardry.entity.living.EntityAIAttackSpell.attemptCastSpell(EntityAIAttackSpell.java:217)
    at electroblob.wizardry.entity.living.EntityAIAttackSpell.func_75246_d(EntityAIAttackSpell.java:191)
```

**Comment by WinDanesz** [comment]
Already fixed
