### ISSUE TITLE
Server Crash with Ancient Evil Wizard

### ISSUE THREAD

**Issue by DoctorZoe** [WinDanesz/AncientSpellcraft#55]
Recently, I've been getting some crashes on my server and the console is pointing to an entity from Ancient Spellcraft.

**Link to the Crash Log (which doesn't include the name of the entity): https://pastebin.com/8CRLcHFz**

**Console log (which includes the name):**
[12:14:43] [Server thread/ERROR] [FML]: Encountered an exception while constructing entity 'ancientspellcraft:evil_class_wizard'
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221]
        at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:305) [EntityEntryBuilder$ConstructorFactory.class:?]
        at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:291) [EntityEntryBuilder$ConstructorFactory.class:?]
        at net.minecraftforge.fml.common.registry.EntityEntry.newInstance(EntityEntry.java:68) [EntityEntry.class:?]
        at net.minecraft.world.biome.Biome$SpawnListEntry.newInstance(Biome.java:655) [anh$c.class:?]
        at net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(WorldEntitySpawner.java:141) [anb.class:?]
        at net.minecraft.world.WorldServer.tick(WorldServer.java:203) [oo.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.IllegalArgumentException: Duplicate id value for 12!
        at net.minecraft.network.datasync.EntityDataManager.register(EntityDataManager.java:106) ~[nb.class:?]
        at com.windanesz.ancientspellcraft.entity.living.EntityEvilClassWizard.entityInit(EntityEvilClassWizard.java:60) ~[EntityEvilClassWizard.class:1.12.2-1.2.1]
        at net.minecraft.entity.Entity.<init>(Entity.java:217) ~[vg.class:?]
        at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:164) ~[vp.class:?]
        at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:90) ~[vq.class:?]
        at net.minecraft.entity.EntityCreature.<init>(SourceFile:21) ~[vx.class:?]
        at net.minecraft.entity.monster.EntityMob.<init>(EntityMob.java:26) ~[ade.class:?]
        at electroblob.wizardry.entity.living.EntityEvilWizard.<init>(EntityEvilWizard.java:81) ~[EntityEvilWizard.class:?]
        at com.windanesz.ancientspellcraft.entity.living.EntityEvilClassWizard.<init>(EntityEvilClassWizard.java:52) ~[EntityEvilClassWizard.class:1.12.2-1.2.1]
        ... 15 more
[12:14:43] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:762) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NullPointerException
        at net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(WorldEntitySpawner.java:149) ~[anb.class:?]
        at net.minecraft.world.WorldServer.tick(WorldServer.java:203) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756) ~[MinecraftServer.class:?]
        ... 4 more

**Comment by DoctorZoe** [comment]
It was a duplicate.
