### ISSUE TITLE
Spell Blade crash on dedicated server (calling client-only method)

### ISSUE THREAD

**Issue by WinDanesz** [WinDanesz/AncientSpellcraft#74]
Server log
`java.lang.NoSuchMethodError: net.minecraft.potion.Potion.func_188408_i()Z
    at com.windanesz.ancientspellcraft.item.ItemBattlemageSword$EnumElementalSwordEffect$5.lambda$greaterPowerOnEntityHit$0(ItemBattlemageSword.java:1192)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
    at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at com.windanesz.ancientspellcraft.item.ItemBattlemageSword$EnumElementalSwordEffect$5.greaterPowerOnEntityHit(ItemBattlemageSword.java:1195)
    at com.windanesz.ancientspellcraft.item.ItemBattlemageSword$EnumElementalSwordEffect.hitEntity(ItemBattlemageSword.java:1381)
    at com.windanesz.ancientspellcraft.item.ItemBattlemageSword.hitEntity(ItemBattlemageSword.java:310)
    at com.windanesz.ancientspellcraft.entity.ai.EntityAIBattlemageMelee.checkAndPerformAttack(EntityAIBattlemageMelee.java:135)
    at com.windanesz.ancientspellcraft.entity.ai.EntityAIBattlemageMelee.updateTask(EntityAIBattlemageMelee.java:124)
    at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:129)
    at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:763)
    at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2359)
    at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:577)
    at net.minecraft.entity.monster.EntityMob.onLivingUpdate(EntityMob.java:45)
    at electroblob.wizardry.entity.living.EntityEvilWizard.onLivingUpdate(EntityEvilWizard.java:209)
    at net.minecraft.entity.EntityLivingBase.TickCentral_TrueOnUpdateTick(EntityLivingBase.java:2179)
    at net.minecraft.entity.EntityLiving.TickCentral_TrueOnUpdateTick(EntityLiving.java:295)
    at net.minecraft.entity.monster.EntityMob.TickCentral_TrueOnUpdateTick(EntityMob.java:50)
    at com.github.terminatornl.tickcentral.api.TickHub.trueOnUpdate(TickHub.java:56)
    at com.github.terminatornl.laggoggles.Main.redirectOnUpdate(Main.java:102)
    at net.minecraft.entity.monster.EntityMob.onUpdate(EntityMob.java)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.redirect$zbi000$updateEntity(World.java:4123)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)`

**Comment by WinDanesz** [comment]
fixed in v1.4.0
