### ISSUE TITLE
Blockweaving does not work, possible incompatibility with VanillaFix

### ISSUE THREAD

**Issue by maxwelllc** [WinDanesz/AncientSpellcraft#9]
Using Ancient Spellcraft 1.1.1 with Electroblobs 4.3.1 on the newest version of Roguelike Adventures and Dungeons. 
Attempting to use the Blockweaving spell throws errors into console. The first location designation works fine - It shows the position is saved - but the second right click fails to work. I'm not familiar with Minecraft modding but I get the sense that this might be a VanillaFix problem. If so, let me know and I'll send it over there, otherwise feel free to ask if there's any more info I can provide. The error in console is below.

> [04:04:00] [Server thread/FATAL] [VanillaFix]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_184429_b(Lnet/minecraft/item/ItemStack;)I
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_275]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_275]
at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_184429_b(Lnet/minecraft/item/ItemStack;)I
at com.windanesz.ancientspellcraft.util.ASUtils.shrinkInventoryStackByOne(ASUtils.java:121) ~[ASUtils.class:?]
at com.windanesz.ancientspellcraft.spell.BlockWeaving.onBlockHit(BlockWeaving.java:145) ~[BlockWeaving.class:?]
at electroblob.wizardry.spell.SpellRay.shootSpell(SpellRay.java:283) ~[SpellRay.class:?]
at com.windanesz.ancientspellcraft.spell.BlockWeaving.cast(BlockWeaving.java:77) ~[BlockWeaving.class:?]
at electroblob.wizardry.item.ItemWand.cast(ItemWand.java:478) ~[ItemWand.class:?]
at electroblob.wizardry.item.ItemWand.onItemRightClick(ItemWand.java:392) ~[ItemWand.class:?]
at net.minecraft.item.ItemStack.useItemRightClick(ItemStack.java:217) ~[aip.class:?]
at net.minecraft.server.management.PlayerInteractionManager.processRightClick(PlayerInteractionManager.java:358) ~[or.class:?]
at net.minecraft.network.NetHandlerPlayServer.processTryUseItem(NetHandlerPlayServer.java:765) ~[pa.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItem.processPacket(SourceFile:32) ~[mb.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItem.processPacket(SourceFile:9) ~[mb.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_275]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_275]
at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
... 5 more

**Comment by WinDanesz** [comment]
Thanks, fixed in the next update

**Comment by WinDanesz** [comment]
Fixed in 1.1.2
